# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'

target 'TopNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TopNews

    pod 'AFNetworking'
    pod 'YYModel', '~> 1.0.4'
    pod 'FMDB', '~> 2.6.2'
    pod 'SSZipArchive', '~> 1.6.2'
    pod 'YYModel', '~> 1.0.4'
    pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier.git'
    pod 'OpenUDID', '~> 1.0.0'
    pod 'ALSystemUtilities', '~> 1.3.4'    

    pod 'MJRefresh', '~> 3.1.12'
    
    pod 'SDWebImage'
    
    
    pod 'YYModel', '~> 1.0.4'
    pod 'MBProgressHUD', '~> 1.0.0'

    pod 'MMDrawerController', '~> 0.6.0'
  
    
    
    
    pod 'FBSDKCoreKit', '~> 4.15.0'
    pod 'FBSDKLoginKit', '~> 4.15.0'
    pod 'FBSDKShareKit', '~> 4.15.0'
    
    pod 'TwitterKit', '~> 1.15.3'

    pod 'KSCrash', '~> 1.8'

    
end
